services:
  webapi:
    build:
      context: .
      dockerfile: Src/Presentation/Template.WebApi/Dockerfile
    container_name: my_dotnet_app
    depends_on:
      - db
      - elasticsearch
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Username=postgres;Password=Minas8gerais@;Database=TemplateCleanArch;SearchPath=public
      - ConnectionStrings__IdentityConnection=Host=db;Port=5432;Username=postgres;Password=Minas8gerais@;Database=TemplateCleanArchIdentity;SearchPath=public
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetcore.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=senhaSegura
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - C:/Users/User/.aspnet/https:/https:ro
    networks:
      - nw

  db:
    image: postgres:16
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Minas8gerais@
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - nw

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - v01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - nw
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://elasticsearch:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.17.4
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 5601:5601
    networks:
      - nw

volumes:
  postgres_data:
  v01:
    driver: local

networks:
  nw:
